version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  minio-server:
    image: minio/minio
    ports:
      - "9001:9000"
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    volumes:
      - minio_data:/data
      - ./minio-cors.json:/config/minio/cors.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  userform:
    build:
      context: ./userform
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      MINIO_ENDPOINT: minio-server:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SSL: ${MINIO_SSL}
      WORLDLINK_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID} 
      WORLDLINK_CLIENT_SECRET: ${VITE_AUTH0_CLIENT_SECRET} 
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
      minio-server:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: pole-finder-frontend
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "443:443"
      - "5173:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HTTPS=true
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_REDIRECT_URI=${VITE_REDIRECT_URI}
    networks:
      - app-network

volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local
  userform_data:
    driver: local
  frontend_data:
    driver: local

networks:
  app-network:
    driver: bridge
