version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: binam
      POSTGRES_PASSWORD: Bhandari
      POSTGRES_DB: binam
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U binam"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  minio-server:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data
    volumes:
      - ./minio-data:/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: binam
      DB_PASSWORD: Bhandari
      DB_NAME: binam
      MINIO_ENDPOINT: "minio-server:9000"
      MINIO_ACCESS_KEY: "9bAjrTWAamQb9zam3trE"
      MINIO_SECRET_KEY: "n85o1uMtF1sZ0hlvQIylSPXQOUKPNX5NVLyuSu2i"
      MINIO_SSL: "false"
    ports:
      - "8080:8080"
